"""Promote staged clean foot-ulcer sources into raw/segmentation/footulcer.

This is the safer replacement path when the old ``raw/segmentation/footulcer``
folder is too mixed to use as the main ulcer boundary dataset.

On the first run, any existing destination folder is moved aside instead of
deleted. On later runs, if the destination was generated by this script, it is
rebuilt in place.
"""

from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path


IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
SCRIPT_NAME = "tools/preprocess/promote_clean_footulcer.py"


@dataclass
class SourceSummary:
    source_name: str
    source_path: str
    images: int
    masks: int
    skipped_missing_mask: int


def find_mask(mask_dir: Path, stem: str) -> Path | None:
    for ext in sorted(IMAGE_EXTS):
        candidate = mask_dir / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    return None


def copy_pair(image_path: Path, mask_path: Path, dst_root: Path) -> None:
    (dst_root / "images").mkdir(parents=True, exist_ok=True)
    (dst_root / "masks").mkdir(parents=True, exist_ok=True)
    image_name = f"{image_path.stem}{image_path.suffix.lower()}"
    mask_name = f"{image_path.stem}{mask_path.suffix.lower()}"
    shutil.copy2(image_path, dst_root / "images" / image_name)
    shutil.copy2(mask_path, dst_root / "masks" / mask_name)


def generated_manifest_path(dst_root: Path) -> Path:
    return dst_root / "source_manifest.json"


def was_generated_by_this_script(dst_root: Path) -> bool:
    manifest_path = generated_manifest_path(dst_root)
    if not manifest_path.exists():
        return False
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    return manifest.get("generated_by") == SCRIPT_NAME


def archive_or_reset(dst_root: Path, archive_root: Path, archive_name: str) -> Path | None:
    if not dst_root.exists():
        return None
    if was_generated_by_this_script(dst_root):
        shutil.rmtree(dst_root)
        return None

    archive_root.mkdir(parents=True, exist_ok=True)
    archive_path = archive_root / archive_name
    if archive_path.exists():
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        archive_path = archive_root / f"{archive_name}_{timestamp}"
    shutil.move(str(dst_root), str(archive_path))
    return archive_path


def promote_sources(source_root: Path, dst_root: Path, source_names: list[str]) -> list[SourceSummary]:
    summaries: list[SourceSummary] = []
    for source_name in source_names:
        src = source_root / source_name
        image_dir = src / "images"
        mask_dir = src / "masks"
        copied = 0
        missing = 0
        if not image_dir.exists() or not mask_dir.exists():
            summaries.append(
                SourceSummary(
                    source_name=source_name,
                    source_path=str(src),
                    images=0,
                    masks=0,
                    skipped_missing_mask=0,
                )
            )
            continue

        for image_path in sorted(p for p in image_dir.iterdir() if p.suffix.lower() in IMAGE_EXTS):
            mask_path = find_mask(mask_dir, image_path.stem)
            if mask_path is None:
                missing += 1
                continue
            copy_pair(image_path, mask_path, dst_root)
            copied += 1

        summaries.append(
            SourceSummary(
                source_name=source_name,
                source_path=str(src),
                images=copied,
                masks=copied,
                skipped_missing_mask=missing,
            )
        )
    return summaries


def write_manifest(
    dst_root: Path,
    source_root: Path,
    archived_path: Path | None,
    summaries: list[SourceSummary],
) -> None:
    manifest = {
        "generated_by": SCRIPT_NAME,
        "source_root": str(source_root),
        "destination": str(dst_root),
        "archived_previous_destination": str(archived_path) if archived_path else None,
        "important_note": (
            "This folder is now the clean footulcer boundary set promoted from "
            "data/raw/segmentation_clean. It intentionally excludes the old mixed "
            "footulcer folder and excludes footulcer_tissue/chronic_bbox weak labels."
        ),
        "sources": [asdict(summary) for summary in summaries],
    }
    dst_root.mkdir(parents=True, exist_ok=True)
    generated_manifest_path(dst_root).write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", default="data/raw/segmentation_clean", type=Path)
    parser.add_argument("--raw-root", default="data/raw/segmentation", type=Path)
    parser.add_argument("--output-name", default="footulcer")
    parser.add_argument(
        "--sources",
        nargs="+",
        default=["FUSeg_FootUlcer", "Medetec_FootUlcer"],
    )
    parser.add_argument("--archive-name", default="footulcer_mixed_old")
    args = parser.parse_args()

    dst_root = args.raw_root / args.output_name
    archived_path = archive_or_reset(
        dst_root=dst_root,
        archive_root=args.raw_root,
        archive_name=args.archive_name,
    )
    summaries = promote_sources(args.source_root, dst_root, args.sources)
    write_manifest(dst_root, args.source_root, archived_path, summaries)

    total_images = sum(summary.images for summary in summaries)
    total_masks = sum(summary.masks for summary in summaries)
    total_missing = sum(summary.skipped_missing_mask for summary in summaries)
    print(
        f"{dst_root}: images={total_images}, masks={total_masks}, "
        f"skipped_missing_mask={total_missing}"
    )
    if archived_path:
        print(f"Archived previous destination: {archived_path}")


if __name__ == "__main__":
    main()
