version: tkr-finetune-v1
run_name: exp_ablation_imagenet_only

data_root: data/processed/tkr
datasets: [TKR_Knee]
image_size: 512
cache_data: true
augmentation: tkr # ← 跟原本實驗一致

model: efficientunet
encoder_name: efficientnet-b3
attention: scse
encoder_weights: imagenet # ← 唯一不同的地方

freeze_encoder_epochs: 5 # 跟原本一致
epochs: 50
lr: 0.00005
batch_size: 8
num_workers: 8
loss_name: bce_dice
grad_clip: 1.0
