# =========================
# Dataset
# =========================
version: wound-finetune-v1
run_name: run2
datasets: [DFU, Cut, Laceration, Abrasion, Chronic]

# =========================
# Finetune
# =========================
pretrained_ckpt: checkpoints/wound-finetune-v1/run1/best.pt

# =========================
# Training
# =========================
epochs: 50
batch_size: 4
num_workers: 4

# =========================
# Optimizer
# =========================
lr: 1e-5

# =========================
# Strategy
# =========================
freeze_epochs: 10
